### ISSUE TITLE
Put models in starblast examples?

### ISSUE THREAD

**Issue by thisjaiden** [rvan-der/Starblast.io-modding#1]
There is some nice stuff here, you could put up a pull request to have these models added to https://github.com/pmgl/starblast-modding under /objects/rvan-der, but this is just a suggestion. You can close this if you would prefer your models to be kept here.

**Comment by rvan-der** [comment]
Hi pizzajacob. Actually all the objets are from strutinsky (Uranus on Discord). I'll leave it up to him to decide!

**Comment by thisjaiden** [comment]
Alright, sounds good. Should I close this issue?

**Comment by rvan-der** [comment]
I could propose to pmgl the maze generator I made though :)

**Comment by thisjaiden** [comment]
Good idea! I think that could be left as it or combined with some of the racing mod's timer/ranking code (with credit of course) and would probobly be accepted into the js examples folder.
